"""create_tenant_tables

Revision ID: 5971b00fbe99
Revises: c8addbc0f448
Create Date: 2026-02-06 01:55:51.124151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5971b00fbe99'
down_revision: Union[str, None] = 'c8addbc0f448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Organizations
    op.create_table('organizations',
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('billing_email', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)

    # Create Tenants
    op.create_table('tenants',
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('tenant_id'),
        sa.UniqueConstraint('organization_id', 'slug', name='uc_org_slug')
    )
    op.create_index(op.f('ix_tenants_organization_id'), 'tenants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)

    # Create API Keys
    op.create_table('api_keys',
        sa.Column('key_id', sa.UUID(), nullable=False),
        sa.Column('access_key_id', sa.String(length=255), nullable=False),
        sa.Column('secret_hash', sa.String(length=255), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index(op.f('ix_api_keys_access_key_id'), 'api_keys', ['access_key_id'], unique=True)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)

    op.create_index(op.f('ix_accounts_document_id'), 'accounts', ['document_id'], unique=False)
    op.create_index(op.f('ix_accounts_organization_id'), 'accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.drop_constraint('accounts_document_id_fkey', 'accounts', type_='foreignkey')
    op.drop_constraint('accounts_organization_id_fkey', 'accounts', type_='foreignkey')

    # tenants already created, so we can FK to it
    op.create_foreign_key(None, 'accounts', 'tenants', ['tenant_id'], ['tenant_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'accounts', 'documents', ['document_id'], ['document_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'accounts', 'organizations', ['organization_id'], ['organization_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('admin_audit_log', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_admin_audit_log_admin_user_id'), 'admin_audit_log', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_tenant_id'), 'admin_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_timestamp'), 'admin_audit_log', ['timestamp'], unique=False)
    # Removed redundant drop_constraint/create_index for api_keys as we created table above
    # op.drop_constraint('api_keys_access_key_id_key', 'api_keys', type_='unique')
    # op.create_index(op.f('ix_api_keys_access_key_id'), 'api_keys', ['access_key_id'], unique=True)
    # op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    # op.drop_constraint('api_keys_organization_id_fkey', 'api_keys', type_='foreignkey')
    # op.drop_constraint('api_keys_tenant_id_fkey', 'api_keys', type_='foreignkey')
    # op.create_foreign_key(None, 'api_keys', 'tenants', ['tenant_id'], ['tenant_id'], onupdate='CASCADE', ondelete='CASCADE')
    # op.create_foreign_key(None, 'api_keys', 'organizations', ['organization_id'], ['organization_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.drop_constraint('documents_organization_id_fkey', 'documents', type_='foreignkey')
    op.drop_constraint('documents_tenant_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'tenants', ['tenant_id'], ['tenant_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'documents', 'organizations', ['organization_id'], ['organization_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_index(op.f('ix_holdings_account_id'), 'holdings', ['account_id'], unique=False)
    op.create_index(op.f('ix_holdings_document_id'), 'holdings', ['document_id'], unique=False)
    op.create_index(op.f('ix_holdings_organization_id'), 'holdings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_holdings_tenant_id'), 'holdings', ['tenant_id'], unique=False)
    op.drop_constraint('holdings_account_id_fkey', 'holdings', type_='foreignkey')
    op.drop_constraint('holdings_tenant_id_fkey', 'holdings', type_='foreignkey')
    op.drop_constraint('holdings_document_id_fkey', 'holdings', type_='foreignkey')
    op.drop_constraint('holdings_organization_id_fkey', 'holdings', type_='foreignkey')
    op.create_foreign_key(None, 'holdings', 'documents', ['document_id'], ['document_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'holdings', 'organizations', ['organization_id'], ['organization_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'holdings', 'tenants', ['tenant_id'], ['tenant_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'holdings', 'accounts', ['account_id'], ['account_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'),
               existing_nullable=False)
    op.drop_index('ix_jobs_composite_tenant', table_name='jobs')
    op.create_index(op.f('ix_jobs_client_id'), 'jobs', ['client_id'], unique=False)
    op.create_index(op.f('ix_jobs_file_sha256'), 'jobs', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_tenant_status_created', 'jobs', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_unique_constraint('loc_client_idempotency_uc', 'jobs', ['client_id', 'idempotency_key'])
    op.drop_constraint('fk_jobs_organizations', 'jobs', type_='foreignkey')
    op.drop_constraint('fk_jobs_tenants', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'tenants', ['tenant_id'], ['tenant_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'jobs', 'organizations', ['organization_id'], ['organization_id'], onupdate='CASCADE', ondelete='RESTRICT')
    # Removed redundant tenants constraints as table created above
    # op.drop_constraint('organizations_slug_key', 'organizations', type_='unique')
    # op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # op.drop_constraint('uq_tenant_org_slug', 'tenants', type_='unique')
    # op.create_index(op.f('ix_tenants_organization_id'), 'tenants', ['organization_id'], unique=False)
    # op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    # op.create_unique_constraint('uc_org_slug', 'tenants', ['organization_id', 'slug'])
    # op.drop_constraint('tenants_organization_id_fkey', 'tenants', type_='foreignkey')
    # op.create_foreign_key(None, 'tenants', 'organizations', ['organization_id'], ['organization_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('BUY', 'SELL', 'DIVIDEND', 'INTEREST', 'TRANSFER_IN', 'TRANSFER_OUT', 'FEE', 'OTHER', name='transactiontype'),
               existing_nullable=False)
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_document_id'), 'transactions', ['document_id'], unique=False)
    op.create_index(op.f('ix_transactions_organization_id'), 'transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_transactions_tenant_id'), 'transactions', ['tenant_id'], unique=False)
    op.drop_constraint('transactions_document_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_organization_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_tenant_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_account_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['account_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'organizations', ['organization_id'], ['organization_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'transactions', 'tenants', ['tenant_id'], ['tenant_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'transactions', 'documents', ['document_id'], ['document_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_account_id_fkey', 'transactions', 'accounts', ['account_id'], ['account_id'], ondelete='CASCADE')
    op.create_foreign_key('transactions_tenant_id_fkey', 'transactions', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='RESTRICT')
    op.create_foreign_key('transactions_organization_id_fkey', 'transactions', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.create_foreign_key('transactions_document_id_fkey', 'transactions', 'documents', ['document_id'], ['document_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_transactions_tenant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_organization_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_document_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.alter_column('transactions', 'type',
               existing_type=sa.Enum('BUY', 'SELL', 'DIVIDEND', 'INTEREST', 'TRANSFER_IN', 'TRANSFER_OUT', 'FEE', 'OTHER', name='transactiontype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key('tenants_organization_id_fkey', 'tenants', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.drop_constraint('uc_org_slug', 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_organization_id'), table_name='tenants')
    op.create_unique_constraint('uq_tenant_org_slug', 'tenants', ['organization_id', 'slug'])
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_unique_constraint('organizations_slug_key', 'organizations', ['slug'])
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('fk_jobs_tenants', 'jobs', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_jobs_organizations', 'jobs', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.drop_constraint('loc_client_idempotency_uc', 'jobs', type_='unique')
    op.drop_index('ix_jobs_tenant_status_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_file_sha256'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_client_id'), table_name='jobs')
    op.create_index('ix_jobs_composite_tenant', 'jobs', ['tenant_id', 'status', 'created_at'], unique=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.create_foreign_key('holdings_organization_id_fkey', 'holdings', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.create_foreign_key('holdings_document_id_fkey', 'holdings', 'documents', ['document_id'], ['document_id'], ondelete='CASCADE')
    op.create_foreign_key('holdings_tenant_id_fkey', 'holdings', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='RESTRICT')
    op.create_foreign_key('holdings_account_id_fkey', 'holdings', 'accounts', ['account_id'], ['account_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_holdings_tenant_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_organization_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_document_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_account_id'), table_name='holdings')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_tenant_id_fkey', 'documents', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='RESTRICT')
    op.create_foreign_key('documents_organization_id_fkey', 'documents', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key('api_keys_tenant_id_fkey', 'api_keys', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.create_foreign_key('api_keys_organization_id_fkey', 'api_keys', 'organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_access_key_id'), table_name='api_keys')
    op.create_unique_constraint('api_keys_access_key_id_key', 'api_keys', ['access_key_id'])
    op.drop_index(op.f('ix_admin_audit_log_timestamp'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_tenant_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_admin_user_id'), table_name='admin_audit_log')
    op.alter_column('admin_audit_log', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key('accounts_organization_id_fkey', 'accounts', 'organizations', ['organization_id'], ['organization_id'], ondelete='RESTRICT')
    op.create_foreign_key('accounts_tenant_id_fkey', 'accounts', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='RESTRICT')
    op.create_foreign_key('accounts_document_id_fkey', 'accounts', 'documents', ['document_id'], ['document_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_organization_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_document_id'), table_name='accounts')
    # ### end Alembic commands ###
