"""Add Phase 2 tables

Revision ID: c540300a7dab
Revises: 5a20da6188c2
Create Date: 2026-02-06 16:38:31.881527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c540300a7dab'
down_revision: Union[str, None] = '5a20da6188c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provisioning_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_slug', sa.String(length=255), nullable=True),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_slug', sa.String(length=255), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('rate_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='provisioningstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('pending_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_rate_limits',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('jobs_per_hour', sa.Integer(), nullable=False),
    sa.Column('api_calls_per_hour', sa.Integer(), nullable=False),
    sa.Column('concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('storage_gb_limit', sa.Integer(), nullable=False),
    sa.Column('custom_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('usage_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('JOB_SUBMITTED', 'API_CALL', 'STORAGE_USED', 'COMPUTE_SECONDS', name='usageeventtype'), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=4), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aggregated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_usage_events_tenant_id'), 'usage_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_usage_events_timestamp'), 'usage_events', ['timestamp'], unique=False)
    op.create_table('usage_records',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('jobs_count', sa.Integer(), nullable=True),
    sa.Column('api_calls_count', sa.Integer(), nullable=True),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=True),
    sa.Column('compute_seconds', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('tenant_id', 'date', name='uc_tenant_date_usage')
    )
    op.create_index(op.f('ix_usage_records_tenant_id'), 'usage_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_tenant_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_usage_events_timestamp'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_tenant_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('tenant_rate_limits')
    op.drop_table('pending_notifications')
    op.drop_table('provisioning_requests')
    # ### end Alembic commands ###
